# Generated by Django 4.1.3 on 2023-11-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub_api', '0002_alter_employee_employee_type_alter_employee_pfp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHubApiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='success', max_length=60)),
                ('message', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='taskhub_api.azureimage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='drivers_license_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskhub_api.employeetype'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('x', 'diverse')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pfp_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskhub_api.azureimage'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
