# Generated by Django 4.1.3 on 2024-01-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub_api', '0004_alter_task_employees_alter_task_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='title',
            field=models.CharField(choices=[('queued', 'queued'), ('in progress', 'in progress'), ('done', 'done')], max_length=20),
        ),
    ]
