# Generated by Django 4.1.3 on 2024-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub_api', '0006_alter_tasktype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('diverse', 'diverse')], max_length=7, null=True),
        ),
    ]
