# Generated by Django 4.1.3 on 2024-01-24 21:04

from django.db import migrations, models
import taskhub_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhub_api', '0008_setup_sampledata_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=taskhub_api.models.current_date),
        ),
    ]
